### ISSUE TITLE
search result

### ISSUE THREAD

**Issue by johangm90** [metowolf/NeteaseCloudMusicApi#1]
how parse the result search i receive something like this
`{"result":"35b1748964af8a7c1d883e3a15a258de76740b4d50b1f1cf6d253a0760a2b3f97c0b4d48ddff6c133a3abf4d0338b10b0b31e2ec6db4bbaa03654e66a0b10b74a5ca3812b374a1a7faa0996ec5792c9883628a441081f43d5b5f0d958c000a2c9c183ab23741cf9899d14f49a69a5fed53118cdd22b6df95894078b27fb1c2508a78aa16e247de3a28ffd9462de710a18abc18851040208489081ae62929af3973e081e8944426a2c526dea1c3adfbff7cca06d8ed6a2c623af445a89187bc7f48d366c3423876ec43f9c5a06e48008c10ec0ac838a8af263e1237dde44ac8668e............................","code":200,"abroad":true}`

**Comment by metowolf** [comment]
Please post your raw post_data :D

**Comment by johangm90** [comment]
what do you mean by raw post_data?
anyway i change this line
$url='http://music.163.com/weapi/cloudsearch/get/web?csrf_token=';
with
$url='http://music.163.com/weapi/search/get/web?csrf_token=';
and it works

**Comment by metowolf** [comment]
I mean you can comment `params`,`encSecKey`,`post data` and `url` here
