### ISSUE TITLE
提示Parse error: syntax error, unexpected '[' in MusicAPI.php on line 96 怎么办

### ISSUE THREAD

**Issue by Leo02** [metowolf/NeteaseCloudMusicApi#4]
index.php内容是

```
<?php
require_once 'MusicAPI.php';
$api = new MusicAPI();
$result = $api->url('729396');
var_dump(json_decode($result));
?>
```

其他的都没改动，为什么会出错呢

**Comment by metowolf** [comment]
应该是你的 PHP 版本太低，不支持 `[]` 的语法，你可以先尝试把所有代码中的 `[]` 改为 `array()`  
晚上我更新一遍，兼容一下。

**Comment by Leo02** [comment]
改为array()不报错了但是全是null...

`{"data":[{"id":729396,"url":null,"br":0,"size":0,"md5":null,"code":404,"expi":1200,"type":null,"gain":0.0,"fee":0,"uf":null,"payed":0,"flag":0,"canExtend":false}],"code":200}`

**Comment by metowolf** [comment]
难道这是地区限定？先确认你的测试环境是否位于中国大陆

**Comment by Leo02** [comment]
应该是，服务器在香港。虾米也是必须要在中国大陆地区。

**Comment by metowolf** [comment]
可以考虑挂个代理，我后面再加个简易的代理接口

**Comment by Leo02** [comment]
嗯，谢谢了
