### ISSUE TITLE
v3的api返回的json似乎并非简单的gzip压缩

### ISSUE THREAD

**Issue by shunf4** [metowolf/NeteaseCloudMusicApi#5]
如题。虽然请求头里面有Accept-Encoding: gzip一句，但经我试验返回的数据不能用gzip解压缩（没有头1F 8B），并且去掉这一句后返回的数据没有变化，所以我猜测应该采用了另一种加密方式

**Comment by metowolf** [comment]
我改了个网页版的 UserAgent 它直接返回明文了，可以暂时无视了。

**Comment by shunf4** [comment]
抱歉，今天再看的时候，发现应该只是gzip加密，有数据头。
应该是我自己这边的问题

**Comment by shunf4** [comment]
再看了一下，发现v3的eapi用了gzip压缩，但是只有 /eapi/song/enhance/player/url 用了目前未知的加密方式
