### ISSUE TITLE
V3 weapi 单曲的参数正确么？

### ISSUE THREAD

**Issue by tsingk** [metowolf/NeteaseCloudMusicApi#6]
c: Json 格式字符串，格式如：[{"id":3377030}]
这个我尝试了下，报参数错误。

但是找了个歌单id试了下 v3 的歌单没问题。

**Comment by metowolf** [comment]
```
array(2) {
  ["c"]=>
  string(19) "[{"id":"27483202"}]"
  ["csrf_token"]=>
  string(0) ""
}
```

这是使用 `var_dump` 出来的参数，测试应该没有问题，如果还是不行可以发一下你的重现参数

**Comment by tsingk** [comment]
已经搞定了哈，我用python写的，少了一步对id的 json.dump

 不过v3里的 song/detail 返回的结果跟你 wiki里  ”网易云音乐API分析 weapi 5. 单曲信息”
返回信息不一样

你可以确认下

**Comment by metowolf** [comment]
感谢提醒，我稍后全部更新一下
