### ISSUE TITLE
抓了几个包尝试解密获取原信息

### ISSUE THREAD

**Issue by bbaa-bbaa** [metowolf/NeteaseCloudMusicApi#9]
然后我崩溃了
params:wMHl2NRSLZswkhm96ud1cYLR1O0P46owJB3I7gSILdx4oVOBpX2Ec7K141ov5q0NTjM0KrDIM9vM0gGRTqxbCTMSU2uIW5cwtSvA4tXC2VAUi0xMaj7g5cLcfQPcYHU1fw2ZrwHAT1P0KlL15LRIOwVC4ZnagrCNNx1K4AM7CpT+BNtl467cgveg8c5KWamhzSwF5PEl4JgRIymA+ourWxHw4nFp8sn7nLKnwCTOGvQ=
encSecKey:14108f6cad95fbef91ae8cd3f89bdc5a95e418a0408bb8e69f2c03eb01fefa02c107b7a205f9a0042c6e6f1c44c02aa60d1bb2a312d5d84f030eb99a72b49b4be0b2c6509d4d2485e2df7bafc6197b6acddb3ae66c63adab1ca99740a4c602bcc2682a56dd6fd645ad2236e75b33a73b98c345a919aefd95db9e3a267ed34c05
大大是如何知道加密的原信息的

**Comment by metowolf** [comment]
合理使用 F12 开发者工具，下断点
